#!/usr/bin/env python3
"""
terrain.py — generate the Stage-4 terrain model variant (mybot_terrain.xml).

Takes the base mybot.xml and injects, as STATIC scene geometry (group 2, so the lidar
rays see it and it collides with the robot):
  * a STAIRCASE of N low steps rising +x from STAIR_X0, with a top platform
  * a ROUGH-GROUND heightfield patch at ROUGH_C (data left flat here; TerrainNavEnv
    re-randomizes model.hfield_data every reset — data lives in the model, and each
    training worker owns its own model copy, so per-env randomization is safe)

The base scene (floor, goal marker, obstacle mocaps, robot) is untouched, so
TerrainNavEnv inherits everything ObstacleNavEnv can do on this model too.
"""
import os

_HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.abspath(os.path.join(_HERE, "..", "mujoco", "mybot.xml"))
DST = os.path.abspath(os.path.join(_HERE, "..", "mujoco", "mybot_terrain.xml"))

# staircase geometry (keep in sync with TerrainNavEnv's goal sampling)
STAIR_X0 = 2.6          # x where the first step starts
STAIR_RISE = 0.04       # per-step height (wheel radius ~0.08 -> climbable with leg help)
STAIR_RUN = 0.30        # per-step depth
STAIR_N = 6             # number of steps (top at 0.24 m)
STAIR_HALFW = 1.0       # half width in y
ROUGH_C = (0.0, -3.2)   # center of the rough patch
ROUGH_HALF = 1.5        # half extent (3 m x 3 m patch)
ROUGH_HMAX = 0.08       # max bump height (m)
HF_RES = 64             # heightfield resolution (nrow = ncol)

_HFIELD_ASSET = (f'    <hfield name="rough" nrow="{HF_RES}" ncol="{HF_RES}" '
                 f'size="{ROUGH_HALF} {ROUGH_HALF} {ROUGH_HMAX} 0.01"/>\n')


def _stairs_xml():
    out = ["    <!-- Stage-4 terrain (generated by terrain.py; group 2 = ray-visible) -->"]
    for i in range(STAIR_N):
        h = STAIR_RISE * (i + 1)
        x = STAIR_X0 + STAIR_RUN * i + 0.15
        out.append(f'    <geom name="step_{i}" type="box" size="0.15 {STAIR_HALFW} {h/2:.4f}" '
                   f'pos="{x:.3f} 0 {h/2:.4f}" rgba="0.62 0.62 0.68 1" group="2"/>')
    top_h = STAIR_RISE * STAIR_N
    top_x = STAIR_X0 + STAIR_RUN * STAIR_N + 0.5
    out.append(f'    <geom name="stair_top" type="box" size="0.5 {STAIR_HALFW} {top_h/2:.4f}" '
               f'pos="{top_x:.3f} 0 {top_h/2:.4f}" rgba="0.62 0.62 0.68 1" group="2"/>')
    out.append(f'    <geom name="rough_patch" type="hfield" hfield="rough" '
               f'pos="{ROUGH_C[0]} {ROUGH_C[1]} 0" rgba="0.45 0.55 0.45 1" group="2"/>')
    return "\n".join(out) + "\n"


def ensure_terrain_model(force=False):
    """Build mybot_terrain.xml from mybot.xml (idempotent; rebuilds if base is newer)."""
    if (not force and os.path.isfile(DST)
            and os.path.getmtime(DST) >= os.path.getmtime(SRC)):
        return DST
    with open(SRC) as f:
        txt = f.read()
    assert "</asset>" in txt and "</worldbody>" in txt, "unexpected mybot.xml structure"
    txt = txt.replace("</asset>", _HFIELD_ASSET + "  </asset>", 1)
    txt = txt.replace("</worldbody>", _stairs_xml() + "  </worldbody>", 1)
    with open(DST, "w") as f:
        f.write(txt)
    return DST


if __name__ == "__main__":
    print("wrote", ensure_terrain_model(force=True))
